runtime: python312

handlers:
- url: /
  secure: always
  static_files: client/index.html
  upload: client/index.html

- url: /wordle
  secure: always
  static_files: client/redirectAddSlash.html
  upload: client/redirectAddSlash.html

- url: /word_puzzle(/(.*))?
  secure: always
  static_files: client/word_puzzle/redirect-to-fractograms.html
  upload: client/word_puzzle/redirect-to-fractograms.html

- url: /fractograms
  secure: always
  static_files: client/redirectAddSlash.html
  upload: client/redirectAddSlash.html

- url: /nbody
  secure: always
  static_files: client/redirectAddSlash.html
  upload: client/redirectAddSlash.html

- url: /(.*)/
  secure: always
  static_files: client/\1/index.html
  upload: client/(.*)/index.html

- url: /(.*)
  secure: always
  static_files: client/\1
  upload: client/(.*)

